#Can config YAML file

# Send configs:
#   can_name: 'str'
#   can_id: True/False
#   can_label: 'str'
#   can_value: 'value'
#   can_period: int 



# dbc_file: './J1939-DBC/J1939_original.dbc'
dbc_file: './J1939-DBC/J1939_demo.dbc'



config_groups:
  can_widget_parameters:
    can_send:
      EngineSpeed:
        can_id: True
        can_label: 'EEC2'
        can_bus: 'can0'
        can_value: 100.0
        can_period: 100

      EngineTemp:
        can_name: 'TestCan'
        can_id: True
        can_label: 'TEST1'
        can_bus: 'can0'
        can_value: 1234.0
        can_period: 0
        can_info: "Testing can"

      EngineRPM:
        get_can_info: True

    can_receive:
      0X0CF004FE:
        can_name: 'EngineSpeed'
        can_id: True
        can_id_dec: True
        can_label: 'EEC1'
        can_data:
        can_value: 0
        full_can: True
        show_arbid: "True"
        can_info: "Engine speed shows"

      0X0F332:
        can_name: 'EngineTemp'
        can_label: 'EET1'
        can_data: '0x9988776655'
        full_can: True
        show_arbid: "True"
        can_info: "Temp of engine"


      0X02345:
        can_label: 'TEST'
        can_data: '0x9988776655'
        full_can: True
        show_arbid: "True"
        can_info: "Temp of engine"