#Can config YAML file

# dbc_file: './J1939-DBC/J1939_original.dbc'
dbc_file: './J1939-DBC/J1939_demo.dbc'


config_groups:
  can_widget_parameters:
    can_send:
      EngineSpeed:
        name: 'EEC1'
        canbus: 'can0'
        value: 100.0

    can_receive:
      0X0CF004FE:
        can_name: 'EngineSpeed'
        can_id: True
        can_id_dec: True
        can_label: 'EEC1'
        can_data:
        can_value: 0
        full_can: True
        show_arbid: "True"
        can_info: "Engine speed shows"

      0X0G332:
        can_name: 'EngineTemp'
        can_label: 'EET1'
        can_data: '0x9988776655'
        full_can: True
        show_arbid: "True"
        can_info: "Temp of engine"


      0X02345:
        can_label: 'TEST'
        can_data: '0x9988776655'
        full_can: True
        show_arbid: "True"
        can_info: "Temp of engine"