---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    datefmt: "%H:%M:%S"
    format: "%(asctime)s %(levelname)-8s [%(filename)s:%(lineno)d] %(message)s"
  compact:
    format: "%(asctime)s %(filename)s %(levelname)s %(message)s"
    datefmt: "%y-%m-%d %H:%M:%S"
  extensive:
    format: "%(asctime)s %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  # info_file_handler:
  #   class: logging.handlers.RotatingFileHandler
  #   level: INFO
  #   formatter: simple
  #   filename: logs/info.log
  #   maxBytes: 10485760 # 10MB
  #   backupCount: 20
  #   encoding: utf8

  warning_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: compact
    filename: logs/warnings.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  # error_file_handler:
  #   class: logging.handlers.RotatingFileHandler
  #   level: ERROR
  #   formatter: extensive
  #   filename: logs/errors.log
  #   maxBytes: 10485760 # 10MB
  #   backupCount: 20
  #   encoding: utf8

loggers:
  my_module:
    level: ERROR
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console, warning_file_handler]
